### ISSUE TITLE
"write callback called multiple times"

### ISSUE THREAD

**Issue by KenEucker** [tomcardoso/gulp-dropbox#3]
Whenever I use this package with gulp I get the error:

`write callback called multiple times`.

I've discovered that the callback within this package is called before dropbox filesUpload completes and also when it completes or when it fails. This means it is always called twice.

I have a fix in place and am creating a PR for it.

**Comment by tomcardoso** [comment]
Addressed in https://github.com/tomcardoso/gulp-dropbox/pull/2. Thanks, @KenEucker!
